### ISSUE TITLE
deoplete#custom#set deprecated

### ISSUE THREAD

**Issue by fennerm** [lionawurscht/deoplete-biblatex#2]
I'm getting a deprecation warning when adding custom biblatex filetypes. Docs should probably be updated to deoplete#custom#source. Thanks!

**Comment by lionawurscht** [comment]
Thanks for letting me know :+1: and sorry for the late reaction. I'm new to this :wink:

**Comment by fennerm** [comment]
No problem, thanks for the plugin :)
