### ISSUE TITLE
Simple instructions

### ISSUE THREAD

**Issue by remembertoremind** [lionawurscht/deoplete-biblatex#3]
Hi!

I have been messing around with several options for handling references in markdowm for pandoc, and nothing really works as expected. I tried to get your plugin to work, but nothing happened and there were no errors after installing plugin and applying the settings. Would it be possible to make a simple instruction for installation and usage? I'm pretty sure I'm missing something obvious, but still :)

Thanks.

**Comment by lionawurscht** [comment]
Hey, of course it would be possible to write some more instructions. However, it would be helpfull to know what exactly you have done so far. Did you get deoplete to work with other plugins? After what kind of input do you expect any suggestions to pop up? This plugin is only supposed to suggest citation keys when you enter some syntax. By default you're supposed to get suggestions after entering '[...', so for example, if you have a citation with the key 'HopperEtAl2019' you would get a suggestion for that after enterin '[H...'.

**Comment by remembertoremind** [comment]
Hi. Thank you soo much for your reply.

First I installed the bibtexparser through the AUR. I don't know if there is any difference between the one for python2, 3 or the git-version? Then I installed the plugins
```
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'lionawurscht/deoplete-biblatex'
```
After adding enabling deoplete at startup it suggests everything all words in neovim, so I guess it works as expected? I have never used any type of autocompletion before in nvim. Then I added the path to my `reference.bib` but all suggestions are only from the document, not from the bib-file.
```
let g:deoplete#enable_at_startup = 1
let g:deoplete#sources#biblatex#bibfile = '~/Dropbox/Documents/literature.bib'   
```
I have checked the path ten times, so I'm pretty sure it's correct. All plugins have been updated but deoplete does not react on `\[(?:[\w,]+:)?`

So, deoplete works as expected but does not look at my references

**Comment by lionawurscht** [comment]
Ah, I didn't read the first time that you are working in a markdown file. By default the plugin is activated only for restructuredtext files. Try putting
```
call deoplete#custom#source('biblatex', 'filetypes', ['markdown'])
```
in your config file. If that still doesn't work, in your working markdown file run `:set filetype?`, then you should get something like ` filetype=markdown`. If there it says something else than markdown just add that to the list of filetypes you want to use this plugin with like: `['markdown', '<somehing else than markdown>']`. You need the python 3 version of the bitexparser. The AUR packages `python-bibtexparser` or `python-bibtexparser-git` should both be fine I guess.

I hope that should help you. If not, could you maybe send me you .bib file so I can try whether it works for me?

**Comment by remembertoremind** [comment]
No problem :) My first post could have been way more clear.

Nvim tells me, that the file I'm working in is `filetype=pandoc`, so I've changed it in the settings but there is no change. When hitting any of the keys like`[` nothing happens. [This is my literature.bib](https://pastebin.com/WXADUnbs). I don't hope the formatting will cause issues, but at least that would be an easy fix.

I use the same bib-file and document with pandoc all the time and pandoc uses the bib-file to arrange the references, which works fine. All I need is some kind of autocompletion :)

**Comment by lionawurscht** [comment]
Well the file is working for me so that's not it. I'm surprised that you're not even getting any sort of error. Sorry if this is such a basic question but you did run `:PlugInstall` after adding the plugin to your config file, right? Also did you follow the instructions at [deoplete](https://github.com/Shougo/deoplete.nvim#requirements)? And did you try out any other deoplete autocompletion sources to see whether those work? To be honest I'm not much of a developer myself. I wrote this plugin since I was in the same situation you are in now but I'm not good at troubleshooting at a distance. Maybe tomorrow I'll find some time to look into this some more. Sorry for not being more helpful right now.

**Comment by remembertoremind** [comment]
Jeez that's weird. Yeah, this is really weird. I have installed the plugins by running `PlugInstall` and done everything mentioned in deoplete. There must be something I have missed. Thanks for your help so far - please let me know if you have any suggestions. I keep looking into this and let you know what I find :)

**Comment by lionawurscht** [comment]
Hey, sorry for not having come back to you. I had a lot to do recently. Did you manage to solve your problems?

I'm gonna close this issue for now. Feel free to reopen it if it still persists.

Then it would be good to know:

1. Do other deoplete sources work? If you haven't downloaded any, could you do try them out?
2. What version of vim are you running?
3. What operating system are you running? (I'm only on linux so it's hard for me to help you f you are running windows ...)
4. How did you install the python bibtexparser? Could you confirm that it works?
5. Have you tried other file types? The fact that you are not getting any errors is strange, so I think the most plausible explanation is that either deoplete or this plugin aren't being loaded.

Again, sorry for the long wait.
