### ISSUE TITLE
Biblatex Fails Reading Abbreviated Month Fields

### ISSUE THREAD

**Issue by PorcelainMouse** [lionawurscht/deoplete-biblatex#4]
When my bib file contains an entry with the 'month' field set to a str value, like 'oct' for October, biblatex throws a very long error.  According to other format checkers, this is valid, but not fully suported by bibtexparer, either.

This is the error:
[deoplete] Traceback (most recent call last):
  File "/home/pdestefa/local/lib/python3.7/site-packages/bibtexparser/bibdatabase.py", line 114, in expand_string
    self.strings[name])
KeyError: 'oct'
...

But, this is still not automatically recognized, upstream, after several issues were reported and closed.  Apparently, you can deal with this by manually configuring "definitions" for month abbreviations for all months when you are configuring the parser.

https://github.com/papis/papis-zotero/issues/8

Unfortunately, I cannot seem to get Zotero or Jabref to normalize to the number or the full month name.

**Comment by lionawurscht** [comment]
Hey, I just added the option to specify any of the boolean options for the BibTexParse in the vim config file in bffec71874678d52f54fc37770aa4a33117c4c98.
`common_string` is the option that should help with your problem, I think. Actually I set that to `1`/`true` by default so you shouldn't even need to change your config file.
For me that stopped the error thrown on `jan` as a value to the month field.
Let me know whether this solves your issue.

**Comment by PorcelainMouse** [comment]
Cool, I will need to wait for it to come through pip, but sounds like it will work.  Thanks much.

**Comment by PorcelainMouse** [comment]
Oh, no, I will just update.  right, let me check...sweet! yes, no errors.  Now I can see how it works.  Many thanks.

**Comment by lionawurscht** [comment]
Perfect. Happy I could help. 😁
